// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmmxrBFKXxTLgZTMHFFxB20nV2_9StB7E',
    appId: '1:1069154753304:web:1db20c467ad1da49991c6d',
    messagingSenderId: '1069154753304',
    projectId: 'takenotes-flutter-project01',
    authDomain: 'takenotes-flutter-project01.firebaseapp.com',
    storageBucket: 'takenotes-flutter-project01.appspot.com',
    measurementId: 'G-6Z380S25F8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2wY210IUUvjHRQhitBnwpR49CUf9TCoY',
    appId: '1:1069154753304:android:44d37a8ff5fb45be991c6d',
    messagingSenderId: '1069154753304',
    projectId: 'takenotes-flutter-project01',
    storageBucket: 'takenotes-flutter-project01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1Qfx7QyPqkW2CMv_fdDdcuVQDIXTKGMw',
    appId: '1:1069154753304:ios:a8a63a6c1c3a2ae4991c6d',
    messagingSenderId: '1069154753304',
    projectId: 'takenotes-flutter-project01',
    storageBucket: 'takenotes-flutter-project01.appspot.com',
    iosBundleId: 'com.tadaas.takenotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1Qfx7QyPqkW2CMv_fdDdcuVQDIXTKGMw',
    appId: '1:1069154753304:ios:a8a63a6c1c3a2ae4991c6d',
    messagingSenderId: '1069154753304',
    projectId: 'takenotes-flutter-project01',
    storageBucket: 'takenotes-flutter-project01.appspot.com',
    iosBundleId: 'com.tadaas.takenotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmmxrBFKXxTLgZTMHFFxB20nV2_9StB7E',
    appId: '1:1069154753304:web:9e77b9f367faa458991c6d',
    messagingSenderId: '1069154753304',
    projectId: 'takenotes-flutter-project01',
    authDomain: 'takenotes-flutter-project01.firebaseapp.com',
    storageBucket: 'takenotes-flutter-project01.appspot.com',
    measurementId: 'G-86G85BGZKC',
  );
}
